package com.app.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.app.model.Products;
import com.app.service.ProductsCrudService;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;


@RestController
@Api(value="SportShoesAPI", description="This is Client SportShoes API, you can login using admin credentials - manage & categorize the products, browse list of all users & search by name/contact and view purchase lists by date and category")
@RequestMapping("/sportshoesapi")

public class ProductsCrudController {
	@Autowired
	private ProductsCrudService prodService;
	
	@ApiOperation("Admin can create a product by passing prodname, price, category, description of shoes Id will be autogenerated")
	@PostMapping(value = "/product")
	public String createProduct(@RequestBody Products prod) {
		
		prodService.createProduct(prod);
		 
		 return "Created product and saved to mysql-Sportyshoes DB - " + prod.toString();
	}
	
	@ApiOperation("Admin can update product name and category of the existing product")
	@PutMapping(value = "/product/{id}")
	public String updatecategory(@PathVariable(value = "id") int id,@Validated @RequestBody Products prod) {
		
		prodService.updatecategory(id,prod);
		 
		 return "Updated product for Id - " + id + " and saved to mysql-Sportyshoes DB - " + prod.toString();
	}
	
	@DeleteMapping(value = "/product/{id}")
	public String deleteProductById(@PathVariable(value = "id")int id) {
		prodService.deleteProductById(id);
		return "Deleted - product with id " +id;
		
	}
	
	@GetMapping(value = "/product/{id}")
	public Products getProductById(@PathVariable(value = "id")int id)
	{
		return prodService.getProductById(id);
	}

}
